language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        -   php: 7.3

before_install:
    - composer self-update

install:
    - composer install

script:
    - composer run-script test

after_success:
    - travis_retry bash <(curl -s https://codecov.io/bash)
